spring:
  datasource:
    url: jdbc:mysql://localhost:3306/myblog?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: Liaoxiaolong@123
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
  redis:
    port: 6379
    host: 114.215.68.43
    password: sVDPyKB7dvgJGANq5Mda
    jedis:
      pool:
        max-active: 100
        max-idle: 5
        max-wait: -1
        min-idle: 0
    database: 0
    timeout: 10000
  session:
    store-type: redis
########## Mybatis 自身配置 ##########
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  # 驼峰命名规范 如：数据库字段是  order_id 那么 实体字段就要写成 orderId
#  configuration:
#  map-underscore-to-camel-case: true
#  ########## 通用Mapper ##########
## 主键自增回写方法,默认值MYSQL,详细说明请看文档
#mapper:
#  identity: MYSQL
#  mappers: tk.mybatis.mapper.common.BaseMapper
#  # 设置 insert 和 update 中，是否判断字符串类型!=''
#  not-empty: true
#  # 枚举按简单类型处理
#  enums-as-simple-type: true
########## 分页插件 ##########
pagehelper:
  helper-dialect: mysql
  params:
    count: countSql
  reasonable: false
  support-methods-arguments: true
